services:
  - type: web
    name: can-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.com  # Update this with your frontend domain
    healthCheckPath: /
    autoDeploy: true 